<a href="https://colab.research.google.com/github/PrachiSinghal86/Introduction-to-Pytorch/blob/master/char_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

In [0]:

# open text file and read in data as `text`
with open('charr.txt', 'r') as f:
    text = f.read()

In [8]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [0]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

In [10]:
encoded[:100]


array([ 6, 53, 54, 18, 44, 71, 12, 46, 17,  0,  0,  0, 62, 54, 18, 18, 73,
       46, 52, 54, 50,  7, 69,  7, 71, 63, 46, 54, 12, 71, 46, 54, 69, 69,
       46, 54, 69,  7, 29, 71, 72, 46, 71, 51, 71, 12, 73, 46, 41, 31, 53,
       54, 18, 18, 73, 46, 52, 54, 50,  7, 69, 73, 46,  7, 63, 46, 41, 31,
       53, 54, 18, 18, 73, 46,  7, 31, 46,  7, 44, 63, 46, 27, 10, 31,  0,
       10, 54, 73, 23,  0,  0, 60, 51, 71, 12, 73, 44, 53,  7, 31])

In [0]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot


In [12]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]
